{{- if .Values.issuer.enabled -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.issuer.name }}
  namespace: {{ .Values.namespace }}
spec:
  acme:
    server: {{ .Values.issuer.acme.server }}
    email: {{ .Values.issuer.acme.email }}
    privateKeySecretRef:
      name: {{ .Values.issuer.acme.privateKeySecretRef.name }}
    solvers:
      - http01:
          ingress:
            ingressClassName: {{ .Values.ingress.classname }}
{{- end }}
