apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: nginx
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: "4.7.0"
    chart: ingress-nginx
    helm:
      values: |
        controller:
          service:
            annotations:
              external-dns.alpha.kubernetes.io/hostname: glivs.com
  syncPolicy:
    automated:
        prune: true
        selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true