apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 58.7.0
    helm:
      values: |
        grafana:
          enabled: true
          ingress:
            enabled: true
            annotations: {
              kubernetes.io/ingress.class: nginx
            }
            hosts:
              - grafana.glivs.com
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: glivs
  labels:
    release: prometheus
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: glivs
  endpoints:
    - port: https
      path: /metrics
      interval: 15s
  namespaceSelector:
    any: true
  syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true