apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: glivs
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: glivs
  endpoints:
    - port: https
      path: /metrics
      interval: 15s
  namespaceSelector:
    any: true
